sudo: required
services:
  - docker
before_install:
  - docker build -t burakaraca/multi-container-docker -f ./client/Dockerfile.dev ./client
script:
  - docker run burakaraca/multi-container-docker npm test  -- --coverage

after_success:
  - docker build -t burakaraca/multi-client ./client
  - docker build -t burakaraca/multi-nginx ./nginx
  - docker build -t burakaraca/multi-server ./server
  - docker build -t burakaraca/multi-worker ./worker
  #log in to the docker cli
  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
  #take those images and push them to Docker Hub
  - docker push burakaraca/multi-client
  - docker push burakaraca/multi-nginx
  - docker push burakaraca/multi-server
  - docker push burkaaraca/multi-worker

